CE103 Algorithms and Programming I HW3: Algorithms.HuffmanAlgorithm.HuffmanTree_mp3 Class Reference
Algorithms.HuffmanAlgorithm.HuffmanTree_mp3 Class Reference
Public Member Functions
void Build (byte[] source)
BitArray Encode (byte[] source)
byte[] Decode (BitArray bits)
bool IsLeaf (Node_mp3 node)
Public Attributes
Dictionary< byte, int > Frequencies = new Dictionary<byte, int>()
Properties
Node_mp3 Root [get, set]
Private Attributes
List< Node_mp3 > nodes = new List<Node_mp3>()
Member Function Documentation
Build()
void Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Build (byte[] source)
References Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Frequencies, Algorithms.HuffmanAlgorithm.Node_mp3.Frequency, Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.nodes, and Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Root.
Decode()
byte [] Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Decode (BitArray bits)
References Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.IsLeaf(), and Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Root.
Encode()
BitArray Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Encode (byte[] source)
References Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Root, and Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
IsLeaf()
bool Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.IsLeaf (Node_mp3 node)
References Algorithms.HuffmanAlgorithm.Node_mp3.Left, and Algorithms.HuffmanAlgorithm.Node_mp3.Right.
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Decode().
Member Data Documentation
Frequencies
Dictionary<byte, int> Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Frequencies = new Dictionary<byte, int>()
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Build().
nodes
List<Node_mp3> Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.nodes = new List<Node_mp3>() private
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Build().
Property Documentation
Root
Node_mp3 Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Root get set
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Build(), Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Decode(), and Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Encode().
The documentation for this class was generated from the following file:
ce100-hw3-sln/Algorithms.cs