CE103 Algorithms and Programming I HW3: Algorithms.HuffmanAlgorithm.Node_mp3 Class Reference
Algorithms.HuffmanAlgorithm.Node_mp3 Class Reference
Represents a node in a Huffman tree used for MP3 compression.
Public Member Functions
List< bool > Traverse_mp3 (byte? symbol, List< bool > data)
Traverse the Huffman tree to find the bit sequence for the specified symbol.
Properties
byte Symbol [get, set]
The symbol represented by this node.
int Frequency [get, set]
The frequency of the symbol represented by this node.
Node_mp3 Left [get, set]
The left child node of this node.
Node_mp3 Right [get, set]
The right child node of this node.
Detailed Description
Represents a node in a Huffman tree used for MP3 compression.
Member Function Documentation
Traverse_mp3()
List<bool> Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3 (byte? symbol, List< bool > data)
Traverse the Huffman tree to find the bit sequence for the specified symbol.
Parameters
symbol The symbol to find the bit sequence for.
data The current bit sequence being built.
Returns
The bit sequence for the specified symbol, or null if the symbol is not found in the tree.
References Algorithms.HuffmanAlgorithm.Node_mp3.Left, Algorithms.HuffmanAlgorithm.Node_mp3.Right, Algorithms.HuffmanAlgorithm.Node_mp3.Symbol, and Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Encode(), and Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
Property Documentation
Frequency
int Algorithms.HuffmanAlgorithm.Node_mp3.Frequency get set
The frequency of the symbol represented by this node.
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.Build().
Left
Node_mp3 Algorithms.HuffmanAlgorithm.Node_mp3.Left get set
The left child node of this node.
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.IsLeaf(), and Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
Right
Node_mp3 Algorithms.HuffmanAlgorithm.Node_mp3.Right get set
The right child node of this node.
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree_mp3.IsLeaf(), and Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
Symbol
byte Algorithms.HuffmanAlgorithm.Node_mp3.Symbol get set
The symbol represented by this node.
Referenced by Algorithms.HuffmanAlgorithm.Node_mp3.Traverse_mp3().
The documentation for this class was generated from the following file:
ce100-hw3-sln/Algorithms.cs