CE103 Algorithms and Programming I HW3: Algorithms.AssemblyGuide Class Reference
Algorithms.AssemblyGuide Class Reference
Public Member Functions
AssemblyGuide ()
void AddItem (List< Item > item)
ArrayList GetAssemblySteps ()
Private Member Functions
void DFS (int id, HashSet< int > visited, Stack< int > stack)
List< int > TopologicalSort ()
Private Attributes
List< Item > steps
Constructor & Destructor Documentation
AssemblyGuide()
Algorithms.AssemblyGuide.AssemblyGuide ()
References Algorithms.AssemblyGuide.steps.
Member Function Documentation
AddItem()
void Algorithms.AssemblyGuide.AddItem (List< Item > item)
References Algorithms.AssemblyGuide.steps.
DFS()
void Algorithms.AssemblyGuide.DFS (int id, HashSet< int > visited, Stack< int > stack) private
References Algorithms.AssemblyGuide.steps.
Referenced by Algorithms.AssemblyGuide.TopologicalSort().
GetAssemblySteps()
ArrayList Algorithms.AssemblyGuide.GetAssemblySteps ()
References Algorithms.Item.Dependencies, Algorithms.AssemblyGuide.steps, and Algorithms.AssemblyGuide.TopologicalSort().
TopologicalSort()
List<int> Algorithms.AssemblyGuide.TopologicalSort () private
References Algorithms.AssemblyGuide.DFS(), Algorithms.Item.Id, and Algorithms.AssemblyGuide.steps.
Referenced by Algorithms.AssemblyGuide.GetAssemblySteps().
Member Data Documentation
steps
List<Item> Algorithms.AssemblyGuide.steps private
Referenced by Algorithms.AssemblyGuide.AddItem(), Algorithms.AssemblyGuide.AssemblyGuide(), Algorithms.AssemblyGuide.DFS(), Algorithms.AssemblyGuide.GetAssemblySteps(), and Algorithms.AssemblyGuide.TopologicalSort().
The documentation for this class was generated from the following file:
ce100-hw3-sln/Algorithms.cs