CE103 Algorithms and Programming I HW3: Algorithms.HuffmanAlgorithm.HuffmanTree Class Reference
Algorithms.HuffmanAlgorithm.HuffmanTree Class Reference
Public Member Functions
void Build (string source)
BitArray Encode (string source)
string Decode (BitArray bits)
bool IsLeaf (Node_Txt node)
Public Attributes
Dictionary< char, int > Frequencies = new Dictionary<char, int>()
Properties
Node_Txt Root [get, set]
Private Attributes
List< Node_Txt > nodes = new List<Node_Txt>()
Member Function Documentation
Build()
void Algorithms.HuffmanAlgorithm.HuffmanTree.Build (string source)
References Algorithms.HuffmanAlgorithm.HuffmanTree.Frequencies, Algorithms.HuffmanAlgorithm.Node_Txt.Frequency, Algorithms.HuffmanAlgorithm.HuffmanTree.nodes, and Algorithms.HuffmanAlgorithm.HuffmanTree.Root.
Decode()
string Algorithms.HuffmanAlgorithm.HuffmanTree.Decode (BitArray bits)
References Algorithms.HuffmanAlgorithm.HuffmanTree.IsLeaf(), Algorithms.HuffmanAlgorithm.Node_Txt.Left, Algorithms.HuffmanAlgorithm.Node_Txt.Right, Algorithms.HuffmanAlgorithm.HuffmanTree.Root, and Algorithms.HuffmanAlgorithm.Node_Txt.Symbol.
Encode()
BitArray Algorithms.HuffmanAlgorithm.HuffmanTree.Encode (string source)
References Algorithms.HuffmanAlgorithm.HuffmanTree.Root, and Algorithms.HuffmanAlgorithm.Node_Txt.Traverse().
IsLeaf()
bool Algorithms.HuffmanAlgorithm.HuffmanTree.IsLeaf (Node_Txt node)
References Algorithms.HuffmanAlgorithm.Node_Txt.Left, and Algorithms.HuffmanAlgorithm.Node_Txt.Right.
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree.Decode().
Member Data Documentation
Frequencies
Dictionary<char, int> Algorithms.HuffmanAlgorithm.HuffmanTree.Frequencies = new Dictionary<char, int>()
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree.Build().
nodes
List<Node_Txt> Algorithms.HuffmanAlgorithm.HuffmanTree.nodes = new List<Node_Txt>() private
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree.Build().
Property Documentation
Root
Node_Txt Algorithms.HuffmanAlgorithm.HuffmanTree.Root get set
Referenced by Algorithms.HuffmanAlgorithm.HuffmanTree.Build(), Algorithms.HuffmanAlgorithm.HuffmanTree.Decode(), and Algorithms.HuffmanAlgorithm.HuffmanTree.Encode().
The documentation for this class was generated from the following file:
ce100-hw3-sln/Algorithms.cs